ci: codeql: Don't try to upload scan-build results
The CodeQL upload-sarif action has now been broken to the point
where it's unusable for clang output, which creates a separate
sarif file for each source file.

    Error: The CodeQL Action does not support uploading multiple
    SARIF runs with the same category. Please update your workflow
    to upload a single run per category. For more information, see
    https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file/

Note for future me:

I tried merging the files into one, but I was merging them so there
were still multiple runs in a single file (instead of multiple files).
The CodeQL action was still unhappy.

    - name: Merge SARIF files
      run: |
       jq -s '{ "$schema": "https://json.schemastore.org/sarif-2.1.0", "version": "2.1.0", "runs": map(.runs) | add }' \
          build/sarif/$(ls build/sarif/)/*.sarif \
          > merged.sarif